spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/dbdb?useSSL=false&serverTimezone=Asia/Seoul
#    username: dbuser
#    password: db1234!
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:dbdb}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USER:dbuser}
    password: ${DB_PASSWORD:db1234!}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  #  Docker Compose 파일 위치를 명시적으로 지정하여
  #  프로젝트 루트에서 실행할 때 파일을 찾지 못하는 문제를 방지
  docker:
    compose:
      file: backend/compose.yaml
      #  docker compose 의존 false
      enabled: false


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
